apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: daprConfig
spec:
  tracing:
    samplingRate: "1"
    stdout: false
    otel:
      endpointAddress: "otel-collector:4317"
      isSecure: false
      protocol: "grpc"